apiVersion: v1
kind: Service
metadata:
  name: uim-sap-cloud-integration-automation
  labels:
    app: uim-sap-cloud-integration-automation
spec:
  selector:
    app: uim-sap-cloud-integration-automation
  ports:
  - name: http
    port: 8098
    targetPort: 8098
  type: ClusterIP
