apiVersion: v1
kind: Service
metadata:
  name: uim-sap-sdi
  labels:
    app: uim-sap-sdi
spec:
  selector:
    app: uim-sap-sdi
  ports:
  - name: http
    port: 8096
    targetPort: 8096
  type: ClusterIP
