apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-aas-config
  labels:
    app: uim-sap-aas
data:
  AAS_HOST: "0.0.0.0"
  AAS_PORT: "8086"
  AAS_BASE_PATH: "/api/autoscaler"
  AAS_SERVICE_NAME: "uim-sap-aas"
  AAS_SERVICE_VERSION: "1.0.0"
  AAS_CF_API: "https://api.cf.example"
  AAS_CF_ORG: "production-org"
  AAS_CF_SPACE: "apps"
