apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-ip-config
  labels:
    app: uim-sap-ip
data:
  IPV_HOST: "0.0.0.0"
  IPV_PORT: "8095"
  IPV_BASE_PATH: "/api/ip"
  IPV_SERVICE_NAME: "uim-sap-ip"
  IPV_SERVICE_VERSION: "1.0.0"
