apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-ip-config
  labels:
    app: uim-sap-ip
data:
  IP_HOST: "0.0.0.0"
  IP_PORT: "8095"
  IP_BASE_PATH: "/api/ip"
  IP_SERVICE_NAME: "uim-sap-ip"
  IP_SERVICE_VERSION: "1.0.0"
