apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-alert-notification-config
  labels:
    app: uim-alert-notification-service
data:
  ALERT_HOST: "0.0.0.0"
  ALERT_PORT: "8097"
  ALERT_BASE_PATH: "/api/alert-notification"
  ALERT_SERVICE_NAME: "uim-alert-notification"
  ALERT_SERVICE_VERSION: "1.0.0"
