apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-mdg-config
  labels:
    app: uim-sap-mdg
data:
  MDG_HOST: "0.0.0.0"
  MDG_PORT: "8087"
  MDG_BASE_PATH: "/api/mdg"
  MDG_SERVICE_NAME: "uim-sap-mdg"
  MDG_SERVICE_VERSION: "1.0.0"
  MDG_DEFAULT_APPROVER: "mdg-approver"
