apiVersion: v1
kind: Service
metadata:
  name: uim-sap-slm
  labels:
    app: uim-sap-slm
spec:
  selector:
    app: uim-sap-slm
  ports:
  - name: http
    port: 8120
    targetPort: 8120
  type: ClusterIP
