apiVersion: v1
kind: Service
metadata:
  name: uim-sap-pre
  labels:
    app: uim-sap-pre
spec:
  selector:
    app: uim-sap-pre
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8093
  type: ClusterIP
