apiVersion: v1
kind: Secret
metadata:
  name: uim-sap-docmgmt-integration-secret
  labels:
    app: uim-sap-docmgmt-integration
type: Opaque
stringData:
  auth-token: "change-me-management"
  encryption-key: "change-me-encryption-key-base64"
