apiVersion: v1
kind: Service
metadata:
  name: uim-sap-docmgmt-integration
  labels:
    app: uim-sap-docmgmt-integration
spec:
  selector:
    app: uim-sap-docmgmt-integration
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8091
  type: ClusterIP
