apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-prm-config
  labels:
    app: uim-prm-service
data:
  PRM_HOST: "0.0.0.0"
  PRM_PORT: "8096"
  PRM_BASE_PATH: "/api/prm"
  PRM_SERVICE_NAME: "uim-prm"
  PRM_SERVICE_VERSION: "1.0.0"
  PRM_DEFAULT_CAPACITY_HOURS: "8"
