apiVersion: apps/v1
kind: Deployment
metadata:
  name: uim-prm-service
  labels:
    app: uim-prm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uim-prm-service
  template:
    metadata:
      labels:
        app: uim-prm-service
    spec:
      containers:
        - name: uim-prm-service
          image: uimsolutions/uim-prm-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: uim-prm-config
          ports:
            - containerPort: 8096
          readinessProbe:
            httpGet:
              path: /api/prm/ready
              port: 8096
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/prm/health
              port: 8096
            initialDelaySeconds: 5
            periodSeconds: 10
