apiVersion: v1
kind: Service
metadata:
  name: uim-prm-service
  labels:
    app: uim-prm-service
spec:
  selector:
    app: uim-prm-service
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP
