apiVersion: v1
kind: Service
metadata:
  name: uim-sap-clg
  labels:
    app: uim-sap-clg
spec:
  selector:
    app: uim-sap-clg
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  type: ClusterIP
