apiVersion: v1
kind: Service
metadata:
  name: uim-sap-cre
  labels:
    app: uim-sap-cre
spec:
  selector:
    app: uim-sap-cre
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8086
  type: ClusterIP
