apiVersion: v1
kind: Secret
metadata:
  name: uim-sap-document-management-secret
  labels:
    app: uim-sap-document-management
type: Opaque
stringData:
  auth-token: "change-me-management"
  encryption-key: "change-me-encryption-key-base64"
