apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-cmg-config
data:
  CMG_HOST: "0.0.0.0"
  CMG_PORT: "8095"
  CMG_BASE_PATH: "/api/cmg"
  CMG_SERVICE_NAME: "uim-sap-cmg"
  CMG_SERVICE_VERSION: "1.0.0"
