apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-sdi-config
data:
  SDI_HOST: "0.0.0.0"
  SDI_PORT: "8096"
  SDI_BASE_PATH: "/api/sitedirectory"
  SDI_SERVICE_NAME: "uim-sdi"
  SDI_SERVICE_VERSION: "1.0.0"
