apiVersion: v1
kind: Service
metadata:
  name: uim-sap-smg
  labels:
    app: uim-sap-smg
spec:
  selector:
    app: uim-sap-smg
  ports:
  - name: http
    port: 8094
    targetPort: 8094
  type: ClusterIP
