apiVersion: v1
kind: Secret
metadata:
  name: uim-sap-audit-log-secret
  labels:
    app: uim-sap-audit-log
type: Opaque
stringData:
  auth-token: "change-me-management"
  oauth-token: "change-me-oauth"
