apiVersion: v1
kind: Service
metadata:
  name: uim-sap-rms
  labels:
    app: uim-sap-rms
spec:
  selector:
    app: uim-sap-rms
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP
