apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-bas-config
data:
  BAS_HOST: "0.0.0.0"
  BAS_PORT: "8088"
  BAS_BASE_PATH: "/api/business-application-studio"
  BAS_SERVICE_NAME: "uim-sap-bas"
  BAS_SERVICE_VERSION: "1.0.0"
  BAS_DEFAULT_REGION: "eu10"
