apiVersion: apps/v1
kind: Deployment
metadata:
  name: uim-sap-bas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uim-sap-bas
  template:
    metadata:
      labels:
        app: uim-sap-bas
    spec:
      containers:
      - name: uim-sap-bas
        image: uim-sap-bas:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: uim-sap-bas-config
        env:
        - name: BAS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: uim-sap-bas-secret
              key: authToken
              optional: true
