apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-cis-config
  labels:
    app: uim-sap-cis
data:
  CIS_HOST: "0.0.0.0"
  CIS_PORT: "8088"
  CIS_BASE_PATH: "/api/cis"
  CIS_SERVICE_NAME: "uim-cis"
  CIS_SERVICE_VERSION: "1.0.0"
  CIS_DEFAULT_AUTH_METHOD: "form"
