apiVersion: v1
kind: Service
metadata:
  name: uim-sap-cis
  labels:
    app: uim-sap-cis
spec:
  selector:
    app: uim-sap-cis
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8088
  type: ClusterIP
