apiVersion: v1
kind: Service
metadata:
  name: uim-sap-dqm
  labels:
    app: uim-sap-dqm
spec:
  selector:
    app: uim-sap-dqm
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8091
  type: ClusterIP
