apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-is-config
  labels:
    app: uim-sap-is
data:
  IS_HOST: "0.0.0.0"
  IS_PORT: "8100"
  IS_BASE_PATH: "/api/is"
  IS_SERVICE_NAME: "uim-sap-is"
  IS_SERVICE_VERSION: "1.0.0"
