apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-is-config
  labels:
    app: uim-sap-is
data:
  INT_HOST: "0.0.0.0"
  INT_PORT: "8100"
  INT_BASE_PATH: "/api/is"
  INT_SERVICE_NAME: "uim-sap-is"
  INT_SERVICE_VERSION: "1.0.0"
