apiVersion: v1
kind: Secret
metadata:
  name: uim-sap-kst-secret
  labels:
    app: uim-sap-kst
type: Opaque
stringData:
  auth-token: "change-me-in-production"
  master-key: "change-me-in-production"
