apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-aem-config
  labels:
    app: uim-sap-aem
data:
  AEM_HOST: "0.0.0.0"
  AEM_PORT: "8088"
  AEM_BASE_PATH: "/api/aem"
  AEM_SERVICE_NAME: "uim-sap-aem"
  AEM_SERVICE_VERSION: "1.0.0"
  AEM_DEFAULT_REGION: "eu10"
