apiVersion: v1
kind: Service
metadata:
  name: uim-sap-mdi
  labels:
    app: uim-sap-mdi
spec:
  selector:
    app: uim-sap-mdi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8092
  type: ClusterIP
