/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*) 
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file. 
* Authors: Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*)
*****************************************************************************************************************/
module uim.sap.identityprovisioning.models.group;

import uim.sap.identityprovisioning;

mixin(ShowModule!());

@safe:

/**
  * Represents a user group in the identity provisioning system.
  * This model is used for both incoming API requests and outgoing responses.
  *
  * Fields:
  * - tenantId: The ID of the tenant to which this group belongs.
  * - groupId: The unique ID of the group (generated by the system).
  * - externalId: An optional external identifier for the group (e.g., from an external system).
  * - groupName: The name of the group (required).
  * - displayName: An optional display name for the group.
  * - description: An optional description of the group.
  * - memberUserIds: An array of user IDs that are members of this group.
  * - sourceSystemId: An optional identifier for the source system of this group.
  * - status: The synchronization status of the group (e.g., "synced", "pending", "error", "skipped").
  * - createdAt: The timestamp when the group was created.
  * - updatedAt: The timestamp when the group was last updated.
  */
class IPVGroup : SAPTenantObject {
  mixin(SAPtenantObject!IPVGroup);

  override bool initialize(Json[string] initData) {
    if (!super.initialize(initData)) {
      return false;
    }

    if ("external_id" in initData && initData["external_id"].isString)
      externalId = initData["external_id"].getString;
    if ("group_name" in initData && initData["group_name"].isString)
      groupName = initData["group_name"].getString;
    if ("display_name" in initData && initData["display_name"].isString)
      displayName = initData["display_name"].getString;
    if ("description" in initData && initData["description"].isString)
      description = initData["description"].getString;
    if ("source_system_id" in initData && initData["source_system_id"].isString)
      sourceSystemId = initData["source_system_id"].getString;
    if ("status" in initData && initData["status"].isString)
      status = initData["status"].getString;
    if ("group_id" in initData && initData["group_id"].isString)
      groupId = initData["group_id"].getString;

    if ("member_user_ids" in initData && initData["member_user_ids"].isArray) {
      foreach (item; initData["member_user_ids"].toArray) {
        if (item.isString)
          memberUserIds ~= item.getString;
      }
    }

    createdAt = Clock.currTime();
    updatedAt = createdAt;

    groupId = randomUUID();

    if ("group_name" in initData && initData["group_name"].isString)
      groupName = initData["group_name"].getString;
    if ("external_id" in initData && initData["external_id"].isString)
      externalId = initData["external_id"].getString;
    if ("display_name" in initData && initData["display_name"].isString)
      displayName = initData["display_name"].getString;
    if ("description" in initData && initData["description"].isString)
      description = initData["description"].getString;
    if ("source_system_id" in initData && initData["source_system_id"].isString)
      sourceSystemId = initData["source_system_id"].getString;
    if ("status" in initData && initData["status"].isString)
      status = initData["status"].getString;
    if ("group_id" in initData && initData["group_id"].isString)
      groupId = initData["group_id"].getString;

    if ("member_user_ids" in initData && initData["member_user_ids"].isArray) {
      foreach (item; initData["member_user_ids"].toArray) {
        if (item.isString)
          memberUserIds ~= item.getString;
      }
    }

    createdAt = Clock.currTime();
    updatedAt = createdAt;
    
    return true;
  }

  UUID groupId;
  UUID externalId;
  string groupName;
  string displayName;
  string description;
  string[] memberUserIds;
  UUID sourceSystemId;
  string status = "synced"; // "synced" | "pending" | "error" | "skipped"

  override Json toJson() {
    auto members = memberUserIds.map!(uid => uid.toString()).array;

    return super.toJson()
      .set("group_id", groupId)
      .set("external_id", externalId)
      .set("group_name", groupName)
      .set("display_name", displayName)
      .set("description", description)
      .set("member_user_ids", members)
      .set("source_system_id", sourceSystemId)
      .set("status", status);
  }
}

IPVGroup groupFromJson(UUID tenantId, Json request) {
  IPVGroup g = new IPVGroup(request);
  g.tenantId = tenantId;

  return g;
}
