/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*) 
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file. 
* Authors: Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*)
*****************************************************************************************************************/
module uim.sap.identityprovisioning.models.job;

import uim.sap.identityprovisioning;

mixin(ShowModule!());

@safe:

/**
  * Represents a provisioning job in the identity provisioning system.
  * This model is used for both incoming API requests and outgoing responses.
  *
  * Fields:
  * - tenantId: The ID of the tenant to which this job belongs.
  * - jobId: The unique ID of the job (generated by the system).
  * - jobName: An optional name for the job.
  * - sourceSystemId: An optional identifier for the source system of this job.
  * - targetSystemIds: An array of identifiers for the target systems of this job.
  * - readMode: The mode of reading data ("full" or "delta").
  * - status: The current status of the job ("pending", "running", "completed", "failed", "cancelled").
  * - usersRead: The number of user records read during the job execution.
  * - usersWritten: The number of user records successfully written to target systems.
  * - usersSkipped: The number of user records skipped during processing.
  * - usersFailed: The number of user records that failed to process.
  * - groupsRead: The number of group records read during the job execution.
  * - groupsWritten: The number of group records successfully written to target systems.
  * - groupsSkipped: The number of group records skipped during processing.
  * - groupsFailed: The number of group records that failed to process.
  * - deltaToken: An opaque token used for delta read mode to track changes since the last run.
  * - startedAt: The timestamp when the job started execution.
  * - completedAt: The timestamp when the job completed execution (if applicable).
 */
class IPVJob : SAPTenantEntity {
  mixin(SAPTenantEntityTemplate!IPVJob);

  override bool initialize(Json[string] initData = null) {
    if (!super.initialize(initData)) {
      return false;
    }

    if ("job_id" in initData && initData["job_id"].isString) {
      jobId = UUID(initData["job_id"].get!string);
    }

    jobName = initData.getString("job_name", "");
    sourceSystemId = initData.getString("source_system_id", "");
    readMode = initData.getString("read_mode", "full");
    deltaToken = initData.getString("delta_token", "");

    if ("target_system_ids" in initData && initData["target_system_ids"].isArray) {
      () @trusted {
        foreach (item; initData["target_system_ids"]) {
          if (item.isString)
            targetSystemIds ~= item.getString;
        }
      }();
    }

    return true;
  }

  UUID jobId;
  string jobName;
  UUID sourceSystemId;
  UUID[] targetSystemIds;
  string readMode = "full"; // "full" | "delta"
  string status = "pending"; // "pending" | "running" | "completed" | "failed" | "cancelled"
  long usersRead = 0;
  long usersWritten = 0;
  long usersSkipped = 0;
  long usersFailed = 0;
  long groupsRead = 0;
  long groupsWritten = 0;
  long groupsSkipped = 0;
  long groupsFailed = 0;
  string deltaToken; // opaque token for delta read mode
  string startedAt;
  string completedAt;

  override Json toJson() {
    auto targets = targetSystemIds.map!(tid => tid.toJson()).array;
    {

      return super.toJson()
        .set("job_id", jobId)
        .set("job_name", jobName)
        .set("source_system_id", sourceSystemId)
        .set("target_system_ids", targets)
        .set("read_mode", readMode)
        .set("status", status)
        .set("users_read", usersRead)
        .set("users_written", usersWritten)
        .set("users_skipped", usersSkipped)
        .set("users_failed", usersFailed)
        .set("groups_read", groupsRead)
        .set("groups_written", groupsWritten)
        .set("groups_skipped", groupsSkipped)
        .set("groups_failed", groupsFailed)
        .set("delta_token", deltaToken)
        .set("started_at", startedAt)
        .set("completed_at", completedAt);
    }

    IPVJob jobFromJson(UUID tenantId, Json request) {
      IPVJob j = new IPVJob(request);
      j.tenantId = tenantId;
      j.jobId = randomUUID();

      if ("job_name" in request && request["job_name"].isString)
        j.jobName = request["job_name"].getString;
      if ("source_system_id" in request && request["source_system_id"].isString)
        j.sourceSystemId = request["source_system_id"].getString;
      if ("read_mode" in request && request["read_mode"].isString)
        j.readMode = request["read_mode"].getString;
      if ("delta_token" in request && request["delta_token"].isString)
        j.deltaToken = request["delta_token"].getString;
      if ("job_id" in request && request["job_id"].isString)
        j.jobId = request["job_id"].getString;

      if ("target_system_ids" in request && request["target_system_ids"].isArray) {
        () @trusted {
          foreach (item; request["target_system_ids"]) {
            if (item.isString)
              j.targetSystemIds ~= item.getString;
          }
        }();
      }

      j.createdAt = Clock.currTime();
      j.updatedAt = j.createdAt;
      return j;
    }
  }
