/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*) 
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file. 
* Authors: Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*)
*****************************************************************************************************************/
module uim.sap.identityprovisioning.models.notification;

import uim.sap.identityprovisioning;

mixin(ShowModule!());

@safe:

/**
  * Represents a notification subscription in the identity provisioning system.
  * Tenants can create subscriptions to receive callbacks for specific events (e.g., job status changes).
  *
  * Fields:
  * - tenantId: The ID of the tenant that owns this subscription.
  * - subscriptionId: The unique ID of the subscription (generated by the system).
  * - sourceSystemId: An optional identifier for the source system related to this subscription.
  * - callbackUrl: The URL to which notifications will be sent when events occur.
  * - eventTypes: An array of event types that this subscription is interested in (e.g., ["job.started", "job.completed"]).
  * - active: A boolean indicating whether this subscription is active or not.
  * - deliveredCount: The number of notifications successfully delivered for this subscription.
  * - failedCount: The number of notifications that failed to deliver for this subscription.
  * - createdAt: The timestamp when the subscription was created.
  * - updatedAt: The timestamp when the subscription was last updated.
 */
struct IPVNotification {
  UUID tenantId;
  UUID subscriptionId;
  UUID sourceSystemId;
  string callbackUrl;
  string[] eventTypes; // e.g., ["job.started", "job.completed", "job.failed"]
  bool active = true;
  long deliveredCount = 0;
  long failedCount = 0;
  string createdAt;
  string updatedAt;

  Json toJson() const {
    Json j = Json.emptyObject;
    j["tenant_id"] = tenantId;
    j["subscription_id"] = subscriptionId;
    j["source_system_id"] = sourceSystemId;
    j["callback_url"] = callbackUrl;

    Json events = Json.emptyArray;
    foreach (evt; eventTypes) {
      events ~= Json(evt);
    }
    j["event_types"] = events;

    j["active"] = active;
    j["delivered_count"] = deliveredCount;
    j["failed_count"] = failedCount;
    j["created_at"] = createdAt;
    j["updated_at"] = updatedAt;
    return j;
  }
}

IPVNotification notificationFromJson(string tenantId, Json request) {
  IPVNotification n;
  n.tenantId = tenantId;
  n.subscriptionId = randomUUID().toString();

  if ("source_system_id" in request && request["source_system_id"].isString)
    n.sourceSystemId = request["source_system_id"].get!string;
  if ("callback_url" in request && request["callback_url"].isString)
    n.callbackUrl = request["callback_url"].get!string;
  if ("active" in request && request["active"].type == Json.Type.bool_)
    n.active = request["active"].get!bool;
  if ("subscription_id" in request && request["subscription_id"].isString)
    n.subscriptionId = request["subscription_id"].get!string;

  if ("event_types" in request && request["event_types"].isArray) {
    () @trusted {
      foreach (item; request["event_types"]) {
        if (item.isString)
          n.eventTypes ~= item.get!string;
      }
    }();
  }

  n.createdAt = Clock.currTime().toISOExtString();
  n.updatedAt = n.createdAt;
  return n;
}
