/****************************************************************************************************************
* Copyright: © 2018-2026 Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*) 
* License: Subject to the terms of the Apache 2.0 license, as written in the included LICENSE.txt file. 
* Authors: Ozan Nurettin Süel (aka UI-Manufaktur UG *R.I.P*)
*****************************************************************************************************************/
module uim.sap.identityprovisioning.models.notification;

import uim.sap.identityprovisioning;

mixin(ShowModule!());

@safe:

/**
  * Represents a notification subscription in the identity provisioning system.
  * Tenants can create subscriptions to receive callbacks for specific events (e.g., job status changes).
  *
  * Fields:
  * - tenantId: The ID of the tenant that owns this subscription.
  * - subscriptionId: The unique ID of the subscription (generated by the system).
  * - sourceSystemId: An optional identifier for the source system related to this subscription.
  * - callbackUrl: The URL to which notifications will be sent when events occur.
  * - eventTypes: An array of event types that this subscription is interested in (e.g., ["job.started", "job.completed"]).
  * - active: A boolean indicating whether this subscription is active or not.
  * - deliveredCount: The number of notifications successfully delivered for this subscription.
  * - failedCount: The number of notifications that failed to deliver for this subscription.
  * - createdAt: The timestamp when the subscription was created.
  * - updatedAt: The timestamp when the subscription was last updated.
 */
class IPVNotification : SAPTenantObject {
  mixin(SAPtenantObject!IPVNotification);

  override bool initialize(Json[string] initData) {
    if (!super.initialize(initData)) {
      return false;
    }

    if ("source_system_id" in request && request["source_system_id"].isString) {
      sourceSystemId = request["source_system_id"].get!string;
    }
    if ("callback_url" in request && request["callback_url"].isString) {
      callbackUrl = request["callback_url"].get!string;
    }
    if ("active" in request && request["active"].isBoolean) {
      active = request["active"].get!bool;
    }
    if ("subscription_id" in request && request["subscription_id"].isString) {
      subscriptionId = request["subscription_id"].get!string;
    }
    else {
      subscriptionId = randomUUID();
    }

    if ("event_types" in request && request["event_types"].isArray) {
      foreach (item; request["event_types"].toArray) {
        if (item.isString) {
          eventTypes ~= item.get!string;
        }
      }
    }
    return true;
  }

  UUID subscriptionId;
  UUID sourceSystemId;
  string callbackUrl;
  string[] eventTypes; // e.g., ["job.started", "job.completed", "job.failed"]
  bool active = true;
  long deliveredCount = 0;
  long failedCount = 0;

  override Json toJson() {
    auto events = eventTypes.map!(e => e.toJson).array;

    return super.toJson()
      .set("tenant_id", tenantId)
      .set("subscription_id", subscriptionId)
      .set("source_system_id", sourceSystemId)
      .set("callback_url", callbackUrl)
      .set("event_types", events)
      .set("active", active)
      .set("delivered_count", deliveredCount)
      .set("failed_count", failedCount)
      .set("created_at", createdAt)
      .set("updated_at", updatedAt);
  }

  static IPVNotification notificationFromJson(UUID tenantId, Json request) {
    IPVNotification n = new IPVNotification(request);
    n.tenantId = tenantId;

    n.createdAt = Clock.currTime();
    n.updatedAt = n.createdAt;
    return n;
  }
}
