apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-task-center-config
data:
  TKC_HOST: "0.0.0.0"
  TKC_PORT: "8096"
  TKC_BASE_PATH: "/api/task-center"
  TKC_SERVICE_NAME: "uim-sap-task-center"
  TKC_SERVICE_VERSION: "1.0.0"
  TKC_DATA_DIR: "/var/lib/uim-task-center"
  TKC_CACHE_FILE: "task-cache.json"
