apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uim-sap-html5-repo-pvc
  labels:
    app: uim-sap-html5-repo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
