apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-atp-config
data:
  ATP_HOST: "0.0.0.0"
  ATP_PORT: "8097"
  ATP_BASE_PATH: "/api/automation-pilot"
  ATP_SERVICE_NAME: "uim-atp"
  ATP_SERVICE_VERSION: "1.0.0"
  ATP_AI_PROVIDER: "mock-genai"
