apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-data-retention-config
  labels:
    app: uim-data-retention-service
data:
  DRM_HOST: "0.0.0.0"
  DRM_PORT: "8110"
  DRM_BASE_PATH: "/api/data-retention"
  DRM_SERVICE_NAME: "uim-data-retention"
  DRM_SERVICE_VERSION: "1.0.0"
