apiVersion: v1
kind: ConfigMap
metadata:
  name: uim-sap-isa-config
  labels:
    app: uim-sap-isa
data:
  ISA_HOST: "0.0.0.0"
  ISA_PORT: "8088"
  ISA_BASE_PATH: "/api/situation-automation"
  ISA_SERVICE_NAME: "uim-isa"
  ISA_SERVICE_VERSION: "1.0.0"
  ISA_DEFAULT_TENANT: "default"
